require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ForwardingsController do

  # This should return the minimal set of attributes required to create a valid
  # Forwarding. As you add validations to Forwarding, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ForwardingsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all forwardings as @forwardings" do
      forwarding = Forwarding.create! valid_attributes
      get :index, {}, valid_session
      assigns(:forwardings).should eq([forwarding])
    end
  end

  describe "GET show" do
    it "assigns the requested forwarding as @forwarding" do
      forwarding = Forwarding.create! valid_attributes
      get :show, {:id => forwarding.to_param}, valid_session
      assigns(:forwarding).should eq(forwarding)
    end
  end

  describe "GET new" do
    it "assigns a new forwarding as @forwarding" do
      get :new, {}, valid_session
      assigns(:forwarding).should be_a_new(Forwarding)
    end
  end

  describe "GET edit" do
    it "assigns the requested forwarding as @forwarding" do
      forwarding = Forwarding.create! valid_attributes
      get :edit, {:id => forwarding.to_param}, valid_session
      assigns(:forwarding).should eq(forwarding)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Forwarding" do
        expect {
          post :create, {:forwarding => valid_attributes}, valid_session
        }.to change(Forwarding, :count).by(1)
      end

      it "assigns a newly created forwarding as @forwarding" do
        post :create, {:forwarding => valid_attributes}, valid_session
        assigns(:forwarding).should be_a(Forwarding)
        assigns(:forwarding).should be_persisted
      end

      it "redirects to the created forwarding" do
        post :create, {:forwarding => valid_attributes}, valid_session
        response.should redirect_to(Forwarding.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved forwarding as @forwarding" do
        # Trigger the behavior that occurs when invalid params are submitted
        Forwarding.any_instance.stub(:save).and_return(false)
        post :create, {:forwarding => {}}, valid_session
        assigns(:forwarding).should be_a_new(Forwarding)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Forwarding.any_instance.stub(:save).and_return(false)
        post :create, {:forwarding => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested forwarding" do
        forwarding = Forwarding.create! valid_attributes
        # Assuming there are no other forwardings in the database, this
        # specifies that the Forwarding created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Forwarding.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => forwarding.to_param, :forwarding => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested forwarding as @forwarding" do
        forwarding = Forwarding.create! valid_attributes
        put :update, {:id => forwarding.to_param, :forwarding => valid_attributes}, valid_session
        assigns(:forwarding).should eq(forwarding)
      end

      it "redirects to the forwarding" do
        forwarding = Forwarding.create! valid_attributes
        put :update, {:id => forwarding.to_param, :forwarding => valid_attributes}, valid_session
        response.should redirect_to(forwarding)
      end
    end

    describe "with invalid params" do
      it "assigns the forwarding as @forwarding" do
        forwarding = Forwarding.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Forwarding.any_instance.stub(:save).and_return(false)
        put :update, {:id => forwarding.to_param, :forwarding => {}}, valid_session
        assigns(:forwarding).should eq(forwarding)
      end

      it "re-renders the 'edit' template" do
        forwarding = Forwarding.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Forwarding.any_instance.stub(:save).and_return(false)
        put :update, {:id => forwarding.to_param, :forwarding => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested forwarding" do
      forwarding = Forwarding.create! valid_attributes
      expect {
        delete :destroy, {:id => forwarding.to_param}, valid_session
      }.to change(Forwarding, :count).by(-1)
    end

    it "redirects to the forwardings list" do
      forwarding = Forwarding.create! valid_attributes
      delete :destroy, {:id => forwarding.to_param}, valid_session
      response.should redirect_to(forwardings_url)
    end
  end

end
